FROM python:2.7
LABEL maintainer="Mohiuddin Mohammed"

COPY ./techtrends /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN ["python3", "init_db.py"]
EXPOSE 3111

# command to run on container start
CMD [ "python", "app.py" ]